### ISSUE TITLE
HELP URGENT

### ISSUE THREAD

**Issue by prodplug** [Berl4n/Telegram-Bot-Shop#2]
Traceback (most recent call last):
  File "C:\Users\audim\PycharmProjects\pythonProject19\app.py", line 2124, in callback_inline
    balance = api.balance[0]
  File "C:\Users\audim\PycharmProjects\pythonProject19\venv\lib\site-packages\SimpleQIWI\Session.py", line 80, in balance
    balances = self.full_balance
  File "C:\Users\audim\PycharmProjects\pythonProject19\venv\lib\site-packages\SimpleQIWI\Session.py", line 70, in full_balance
    return self._get_balance()
  File "C:\Users\audim\PycharmProjects\pythonProject19\venv\lib\site-packages\SimpleQIWI\Session.py", line 128, in _get_balance
    json = response.json()
  File "C:\Users\audim\PycharmProjects\pythonProject19\venv\lib\site-packages\requests\models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\audim\PycharmProjects\pythonProject19\app.py", line 2730, in callback_inline
    test = int(call.data)
ValueError: invalid literal for int() with base 10: 'Check payment 2'

**Comment by famaxth** [comment]
Hello! You have a problem with api balance account. Try to change email address.
